name: Update-proxy-IP

on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - 'ip.txt'
    #   - 'best-ip.txt'
  schedule:
    - cron: '*/30 * * * *'  # 每十分钟运行一次

jobs:
  update_ip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update-proxy-IP
      env:
        ME_GITHUB_TOKEN: ${{ secrets.ME_GITHUB_TOKEN }}
        IPDB: ${{ secrets.IPDB }}
      run: python .github/workflows/Update-proxy-IP.py
